NumPy is the fundamental package for scientific computing in Python. 
It is a Python library that provides a multidimensional array object, 
various derived objects (such as masked arrays and matrices), 
and an assortment of routines for fast operations on arrays, including mathematical, 
logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, 
basic linear algebra, basic statistical operations, random simulation and much more.

NumPy, Python'da bilimsel hesaplama için temel pakettir.
Çok boyutlu bir dizi nesnesi sağlayan bir Python kütüphanesidir,
çeşitli türetilmiş nesneler (maskelenmiş diziler ve matrisler gibi),
ve dizilerde hızlı işlemler için matematiksel,
mantıksal, şekil işleme, sıralama, seçme, G/Ç, ayrık Fourier dönüşümleri,
temel lineer cebir, temel istatistiksel işlemler, rastgele simülasyon ve çok daha fazlası.

In [1]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [2]:
import numpy as np
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [5]:
import numpy as np
np.random.randint(1,10)

5

In [6]:
import numpy as np
arr = np.arange(0,11)

In [7]:
arr[2:5]

array([2, 3, 4])

In [8]:
import numpy as np
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [9]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [10]:
arr_2d[0,2]

15